[selenium]
driver               = "chrome"
headless             = true
headless_window_size = "1920x1080"
logging              = true
log_file             = "selenium.log"
pause_at_end         = true

[server]
url = "http://example.com"
password = "CHANGEME"
username = "ghe-admin"
pat = "CHANGEME"

[classic-pat]
# Use ">>>RANDOM<<<" in the "note" field, to have a randomly generated note
note = ">>>RANDOM<<<"

# Note: Double quotes are used around the keys, because tomllib doesn't like
#       colons in key names unless the key names are double quoted

[classic-pat.scopes]
"repo"                      = true
"repo:status"               = true
"repo_deployment"           = true
"public_repo"               = true
"repo:invite"               = true
"security_events"           = true
"workflow"                  = true
"write:packages"            = true
"read:packages"             = true
"delete:packages"           = true
"admin:org"                 = true
"write:org"                 = true
"read:org"                  = true
"manage_runners:org"        = true
"admin:public_key"          = true
"write:public_key"          = true
"read:public_key"           = true
"admin:repo_hook"           = true
"write:repo_hook"           = true
"read:repo_hook"            = true
"admin:org_hook"            = true
"gist"                      = true
"notifications"             = true
"user"                      = true
"read:user"                 = true
"user:email"                = true
"user:follow"               = true
"delete_repo"               = true
"write:discussion"          = true
"read:discussion"           = true
"admin:enterprise"          = true
"manage_runners:enterprise" = true
"manage_billing:enterprise" = true
"read:enterprise"           = true
"admin:pre_receive_hook"    = true
"site_admin"                = true
"admin:gpg_key"             = true
"admin:ssh_signing_key"     = true

[org]
name = "CHANGEME"
members = ["ghe-admin"]

[github_app]
# Use ">>>RANDOM<<<" in the "name" field, to have a randomly generated name
name = "<<<RANDOM>>>"
# Use ">>>RANDOM<<<" in the "description" field, to have a randomly generated description
description = "<<<RANDOM>>>"
homepage = "https://example.com"
# Comma-separated list of callback URLs:
callback_urls = [""]
expire_user_auth_tokens = true
request_oauth_during_install = false
setup_url = ""
redirect_on_update = false
webhook_active = true
webhook_url = "https://example.com"
webhook_secret = ""
enable_ssl_verification = true
# valid valies: "Only on this account", "Any account"
allow_installation_on = "Only on this account"

[github_app.repository_permissions]
# valid values: "No access", "Read-only", "Read and write"
actions                    = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
administration             = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
checks                     = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
code_scanning_alerts       = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
codespaces                 = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
codespaces_lifecycle_admin = "Read and write"

# valid values: "No access", "Read-only"
codespaces_metadata        = "Read-only"

# valid values: "No access", "Read and write"
codespaces_secrets         = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
commit_statuses            = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
contents                   = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
dependabot_alerts          = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
dependabot_secrets         = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
deployments                = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
discussions                = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
environments               = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
issues                     = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
merge_queues               = "Read and write"

# valid values: "No access", "Read-only"
#
# Note: This permission can only be set to "No access" if every other
#       permission in the Repository Permissions section is set to "No access"
metadata                   = "Read-only"

# valid values: "No access", "Read-only", "Read and write"
packages                   = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
pages                      = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
pre_receive_hooks          = "Read and write"

# valid values: "No access", "Read-only", "Read and write", "Admin"
projects                   = "Admin"

# valid values: "No access", "Read-only", "Read and write"
pull_requests              = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
secret_scanning_alerts     = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
secrets                    = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
single_file                = "Read and write"

# comma-separated filesystem paths to single files your app can access
# NOTE: This will be ignored if single_file="No access"
single_file_paths          = ["foo"]

# valid values: "No access", "Read-only", "Read and write"
variables                  = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
webhooks                   = "Read and write"

# valid values: "No access", "Read-only"
workflows                  = "Read-only"


[github_app.organization_permissions]
# valid values: "No access", "Read-only", "Read and write"
administration                   = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
blocking_users                   = "Read and write"

# valid values: "No access", "Read-only"
events                           = "Read-only"

# valid values: "No access", "Read-only", "Read and write"
members                          = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
organization_codespaces          = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
organization_codespaces_settings = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
organization_dependabot_secrets  = "Read and write"

# valid values: "No access", "Read-only"
plan                             = "Read-only"

# valid values: "No access", "Read-only", "Read and write"
pre_receive_hooks                = "Read and write"

# valid values: "No access", "Read-only", "Read and write", "Admin"
projects                         = "Admin"

# valid values: "No access", "Read-only", "Read and write"
secrets                          = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
self_hosted_runners              = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
team_discussions                 = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
variables                        = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
webhooks                         = "Read and write"


[github_app.account_permissions]
# valid values: "No access", "Read-only", "Read and write"
block_another_user               = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
codespaces_user_secrets          = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
email_addresses                  = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
followers                        = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
gpg_keys                         = "Read and write"

# valid values: "No access", "Read and write"
gists                            = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
git_ssh_keys                     = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
interaction_limits               = "Read and write"

# valid values: "No access", "Read-only"
plan                             = "Read-only"

# valid values: "No access", "Read and write"
profile                          = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
ssh_signing_keys                 = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
starring                         = "Read and write"

# valid values: "No access", "Read-only", "Read and write"
watching                         = "Read and write"

[github_app.subscribe_to_events]
meta                           = true
security_advisory              = true
branch_protection_rule         = true
code_scanning_alert            = true
check_run                      = true
check_suite                    = true
commit_comment                 = true
create                         = true
discussion                     = true
discussion_comment             = true
delete                         = true
dependabot_alert               = true
deploy_key                     = true
deployment                     = true
deployment_review              = true
deployment_status              = true
fork                           = true
gollum                         = true
issue_comment                  = true
issues                         = true
label                          = true
milestone                      = true
member                         = true
membership                     = true
merge_group                    = true
merge_queue_entry              = true
organization                   = true
page_build                     = true
project                        = true
project_card                   = true
project_column                 = true
projects_v2_item               = true
public                         = true
pull_request                   = true
pull_request_review            = true
pull_request_review_comment    = true
pull_request_review_thread     = true
push                           = true
registry_package               = true
release                        = true
repository                     = true
repository_dispatch            = true
security_and_analysis          = true
secret_scanning_alert          = true
secret_scanning_alert_location = true
star                           = true
status                         = true
team                           = true
team_add                       = true
watch                          = true
workflow_dispatch              = true
workflow_job                   = true
workflow_run                   = true